import Head from "next/head";
import { Header, Nav } from "@/layout";

const App = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Archive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <Nav />
        <Component {...pageProps} />
      </>
    </>
  );
};

export default App;
